#! /bin/bash

# Uses assert.sh for bash script testing
# credit to: torokmark @ https://github.com/torokmark/assert.sh


SOURCE="${BASH_SOURCE[0]:-$0}" 
while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done # resolve symlinks
BASE="$( cd -P "$( dirname "$SOURCE" )" && pwd )" 


# shellcheck source=assert.sh
source "$BASE"/assert.sh

OLD_CHAR="$BASE/old_charea"
NEW_CHAR="$BASE/../charea"

# $1 = filepath
run_test_on_file () {
    echo -e "\033[0;33mrunning test on $1\033[0m"
    old_output="$($OLD_CHAR "$1")"
    new_output="$($NEW_CHAR "$1")"
    assert_eq "$old_output" "$new_output" "File names don't match for file '$1'!"
    
    old_output="$($OLD_CHAR -g "$1")"
    new_output="$($NEW_CHAR -g "$1")"
    assert_eq "$old_output" "$new_output" "File names don't match for file '$1' w/ -g!"
    
    old_output="$($OLD_CHAR -m "$1")"
    new_output="$($NEW_CHAR -m "$1")"
    assert_eq "$old_output" "$new_output" "File names don't match for file '$1' w/ -m!"
    
    old_output="$($OLD_CHAR -mg "$1")"
    new_output="$($NEW_CHAR -mg "$1")"
    assert_eq "$old_output" "$new_output" "File names don't match for file '$1' w/ -mg!"
}

for file in "$BASE"/files/*;
do
    run_test_on_file "$file"
done

echo -e "\033[0;32mAll tests passed!\033[0m"