#! /bin/bash

# Uses assert.sh for bash script testing
# credit to: torokmark @ https://github.com/torokmark/assert.sh


SOURCE="${BASH_SOURCE[0]:-$0}" 
while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done # resolve symlinks
BASE="$( cd -P "$( dirname "$SOURCE" )" && pwd )" 


# shellcheck source=assert.sh
source "$BASE"/assert.sh


OLD_CHAR="$BASE/old_charea"
NEW_CHAR="$BASE/../charea"

ONE_BAND_OLD="$($OLD_CHAR files/single_band.area)"
ONE_BAND_NEW="$($NEW_CHAR files/single_band.area)"

assert_eq "$ONE_BAND_NEW" "$ONE_BAND_OLD" "Normal one band names are not equal!"

GREG_OLD="$($OLD_CHAR -g files/single_band.area)"
GREG_NEW="$($NEW_CHAR -g files/single_band.area)"

assert_eq "$GREG_OLD" "$GREG_NEW" "One band gregorian names are not equal!"

MONTH_OLD="$($OLD_CHAR -m files/single_band.area)"
MONTH_NEW="$($NEW_CHAR -m files/single_band.area)"

assert_eq "$MONTH_OLD" "$MONTH_NEW" "One band month names are not equal!"

echo -e "\033[0;32m All tests passed!\033[0m"